# Create conda environment with: conda env create -f environment.yml
# Then activate it: conda activate my_env_name

name: my_env_name
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - aiohttp
  - numpy=2.2.4
  - pandas=2.2.1
  - scipy=1.12.0
  - matplotlib=3.8.3
  - seaborn=0.13.2
  - tqdm=4.66.2
  - toolz=0.12.1
  - pandas-stubs=2.2.1.240316
  - pyarrow=15.0.2
  - toml=0.10.2
  - tornado=6.4
  - typing-extensions=4.10.0
  - tzdata=2024.1
  - pip